### ISSUE TITLE
How can I make it use multiple GPUs ?

### ISSUE THREAD

**Issue by aditya-manit** [HarukaMa/aleo-prover#12]
2022-12-06T10:09:02.616521Z  INFO aleo_prover::prover: Received new work: epoch 617                                                                                                                                            2022-12-06T10:09:02.616541Z  WARN aleo_prover::prover: This version of the prover is only using the first GPU

I am on tetsnet3-direct-cuda branch and even after passing -g 0 -g 1 it's giving me the above log message, is there any other version of prover which utilizes all gpus ? 

Also its only using 3% of my gpu memory from what I can see.

**Comment by HarukaMa** [comment]
It seems you could run multiple instances of the prover with `CUDA_VISIBLE_DEVICES=<id>` to choose which GPU it will run on, like:
```sh
CUDA_VISIBLE_DEVICES=0 ./aleo-prover (...) -g 0 (...)
CUDA_VISIBLE_DEVICES=1 ./aleo-prover (...) -g 0 (...)
...
```

I can't test it but you should keep it as `-g 0`.

**Comment by aditya-manit** [comment]
I see, any clues about it using very only 40% of GPU ? and very less memory.

How can I make it use all of my GPU ?

**Comment by aditya-manit** [comment]
or did you mean to utilize the GPU fully I should run multiple instances ?

**Comment by HarukaMa** [comment]
You could try to run multiple instances for now, but the CPU might become the bottleneck then.

**Comment by HarukaMa** [comment]
Closing, reopen if there is still issue
