### ISSUE TITLE
error: no matching package named `snarkos-node-messages` found

### ISSUE THREAD

**Issue by thuandm1** [HarukaMa/aleo-prover#14]
when i join node aleo to pool it show like that, pls support me fix
cargo build --release
error: no matching package named `snarkos-node-messages` found
location searched: https://github.com/AleoHQ/snarkOS.git?rev=8f7f6d9#8f7f6d99
required by package `aleo-prover v0.5.1 (/root/aleo-prover)`

**Comment by HarukaMa** [comment]
See troubleshooting section in pool guide
