### ISSUE TITLE
CUDA  failed

### ISSUE THREAD

**Issue by kubowoo** [HarukaMa/aleo-prover#6]
Error loading cuda program: IO(Os { code: 2, kind: NotFound, message: "No such file or directory" })
CUDA failed, moving to the next MSM method
CUDA failed, moving to the next MSM method
CUDA failed, moving to the next MSM method

**Comment by fgy58963** [comment]
you are compile with the wrong branch

**Comment by HarukaMa** [comment]
please provide more logs and info and reopen
